editorconfig.el
=> Report error when unable to find editorconfig executable

editorconfig.el
=> Adjust shift width for Evil mode

editorconfig.el
http://www.gnu.org/software/emacs/manual/html_node/emacs/Regexps.html
=> Use \' instead of $

editorconfig.el
=> Add slim-mode to editorconfig-indentation-alist

editorconfig.el
=> Add jade-mode to editorconfig-indentation-alist

editorconfig.el
This PR should fix https://github.com/editorconfig/editorconfig-emacs/issues/40
I'll check if there is any regression later.
=> Use hook type for custom-hooks defcustom

Makefile, ert-tests/editorconfig-core-handle.el, ert-tests/editorconfig-core.el, ert-tests/metadata.el
Simplify test code and fix test case name.
Only includes changes for testing.
* Check package metadata using ert framework instead of adding sexp in Makefile
* Fix some test case name
=> Fix test code

README.md, editorconfig.el
Is there any special reason we do not have support for this ? :)
=> Charset support

editorconfig.el
=> Add tcl-mode indentation support

editorconfig.el
=> Add PostScript indentation support

editorconfig.el
=> Add ess-mode indentation support

editorconfig.el
A major-mode for editing .editorconfig file :sunglasses:
=> Add editorconfig-conf-mode

Makefile, bin/editorconfig-el, editorconfig-core-handle.el, editorconfig-core.el, editorconfig-fnmatch.el, editorconfig.el
Recently I started to think it is a little confusing to generate three packages from one repository.
And #80 was reported so I'll merge them into one multifile package :smile_cat: 
I'll merge this after MELPA PR is merged.
=> Fix dependencies for one multifile package

editorconfig.el
For [crystal-mode](https://github.com/jpellerin/emacs-crystal-mode)
=> Add crystal-mode to editorconfig-indentation-alist

editorconfig.el
@10sr Can you review this PR? Thanks!
=> Refactor editorconfig-conf-mode

editorconfig.el
=> Derive editorconfig-conf-mode from conf-unix-mode

editorconfig.el
Fix #83.
@10sr Can you review this? Thanks!
=> Create a syntax table for editorconfig-conf-mode.

editorconfig.el
For [julia-mode](https://github.com/JuliaLang/julia-emacs)
=> Add julia-mode to editorconfig-indentation-alist

editorconfig-core-handle.el
=> Copy properties alist before using them

editorconfig-core-handle.el, editorconfig-core.el, editorconfig.el
=> Revert "Use truename for editorconfig name"

README.md
Add instructions to README to setup use-package with editorconfig.
Thanks!
=> Add use-package usage to documentation

editorconfig.el
Trivial fix for [Customize Interface](https://www.gnu.org/software/emacs/manual/html_node/emacs/Easy-Customization.html).
=> Modify defgroup tag

editorconfig.el
Variables from https://github.com/haskell/haskell-mode/blob/master/haskell-indentation.el
=> Support haskell-indentation minor mode

.gitmodules, ert-tests/editorconfig.el
=> Add editorconfig-mode test

editorconfig-core.el, editorconfig.el
=> Add function to open nearest .editorconfig file

editorconfig.el
```lisp
web-mode-attr-indent-offset
web-mode-attr-value-indent-offset
web-mode-sql-indent-offset
```
=> Web-mode: Add v15 missing indent

editorconfig.el
For [pug-mode](https://github.com/hlissner/emacs-pug-mode)
=> Add support for pug-mode

editorconfig.el
=> Add csharp-mode support

Makefile, docs/editorconfig.info
=> Add texinfo doc

.travis.yml, Makefile
Use evm to install emacs so that emacs25 and 26 can be used for test
=> Update travis config file

Makefile
=> Update plugin-tests submodule

editorconfig.el
Adds [rustic-mode](https://github.com/brotzeit/rustic) support.
=> Add rustic-mode to editorconfig-indentation-alist

editorconfig.el
=> Update hook docstrings

README.md, editorconfig.el
=> Use elisp core by default

editorconfig-conf-mode.el
=>  Add conf-mode abbrev-table definitions

README.md
=> Update README to help bootstrap users

editorconfig.el
Move aliases before their referents.
----
#
=> Silence byte-compiler warnings

editorconfig.el
=> Do not run editorconfig-apply on recentf-save-file

editorconfig.el
https://github.com/editorconfig/editorconfig-emacs/pull/234#issuecomment-732497396
https://github.com/editorconfig/editorconfig-emacs/pull/108#issuecomment-763508743
=> Stop excluding remote files by default

editorconfig.el
[Meson](https://mesonbuild.com/) is an open source build system.
meson-mode: https://github.com/wentasah/meson-mode
=> Add meson-mode indentation rule

README.md
=> Update README for NonGNU ELPA repository

.github/workflows/build.yaml
Should test with the latest minor version.
=> tests(build.yml): Use latest minor version number

editorconfig.el
=> Fix package load for use-package usage

editorconfig.el
=> Check `filename` rather than `buffer-file-name` for consistency

README.md
Remove unnecessary newlines, and update development instructions.
=> docs(README.md): Update development instructions

editorconfig-conf-mode.el, editorconfig-core-handle.el, editorconfig-core.el, editorconfig-fnmatch.el, editorconfig.el
=> chore: Update copyright year

editorconfig.el
In addition to checking parent mode
Fixes #294
=> Check mode-class property for special modes

.github/workflows/build.yaml
=> test: Emacs 29.1

editorconfig.el
Add support for [elixir-ts-mode](https://github.com/wkirschbaum/elixir-ts-mode).
=> Add support for Elixir TS mode

.github/workflows/build.yaml
Seems they are not available anymore
https://github.com/purcell/nix-emacs-ci/issues/267
=> Remove some macos-11 cases from test target

editorconfig-tools.el
=> Add autoload cookie to editorconfig-mode-apply
