- editorconfig.el
As @johan has pointed out in my previous commit, the regex to enable syntax highlighting in .editorconfig files was not specific enough. This minor change ensures that only .editorconfig files are selected and avoid any odd anomalies.
> Make regex for .editorconfig file name detection more accurate

- README.md
- editorconfig.el
This PR has two changes:
1. Define minor-mode named `editotconfig-mode`
Now EditorConfig properties will be applied only when this mode is enabled
2. Use prefix `editorconfifg-` instead of `edconf-`
Usually, when an Emacs package is loaded with `(require 'package-a)`, then all symbols defined there will have a prefix `package-a-`. I think we should follow this convention.
Old variables are marked obsolete.
> Define minor-mode & Use prefix editorconfig-

- editorconfig.el
Make `editorconfig-apply` return immediately when `buffer-file-name` is nil.
This PR may fix the exception described in #44 :smiley_cat: : 
edconf-get-properties: Wrong type argument: stringp, nil
> Do nothing when current buffer does not visit any file

- editorconfig.el
Emacs reacts strangely if `after-change-major-mode-hook` is there: even `M-x` won't work. Removing `after-change-major-mode-hook` would solve the problem (which is removing line 336 in the new version). What is the problem with it?
> Apply settings on major mode change

- editorconfig.el
Changed editorconfig-get-properties to set default-directory to "/"
before calling create-process.  Create-process tries to set the current
directory from default-directory and will error out if this directory
doesn't exist.  This was causing editorconfig-get-properties to fail
when visiting a file in a directory that doesn't exist (yet).
Also use with-temp-buffer to create and manage the temporary buffer used
by editorconfig-get-properties instead of duplicating that functionaily
by hand.
Fixes #35
> Don't error out if default-directory doesn't exist.

- editorconfig.el
'setq-local' was introduced at Emacs 24.3.
> Fix for older Emacs

- README.md
- editorconfig-core.el
- editorconfig.el
Some trivial fixes
* Fix docstring warnings reported by flycheck
* Fix commentary of editorconfig-core
* Make `editorconfig-apply` an interactive command
* I think this is very useful: you can apply new EditorConfig properties without re-visiting the file
* Fix editorconfig.el indent
* Add document about running test
> Misc fixes

- editorconfig-core-handle.el
- editorconfig.el
* Throw errors when
* editorconfig executable was not found
* failed to parse .editorconfig
* Catch errors thrown from editorconfig-get-properties-function and show it with display-warning
> Throw error when broken conf & refactor error handlings

- editorconfig.el
I found that we need not use find-file-hook when after-change-major-mode-hook is used because after-change-major-mode-hook is also called just after visiting files.
Currently editorconfig-apply is always called twice or more when visiting a file.
I'll leave the dolist loop as is so that we can easily add other hooks when we want :-)
> Remove find-file-hook

- editorconfig.el
This simply adds rust-mode support for indentation.
Thanks for the work on this plugin! It's a lifesaver with all of emacs' indentation variables.
> Add support for rust-mode indentation

- editorconfig.el
https://github.com/fxbois/web-mode/blob/master/web-mode.el#L53
`web-mode-block-padding` defines
> Multi-line block (PHP, ruby, java, python, asp, etc.) left padding.
Without this defined, format goes like this:
```
<%!
from views.utils import static, istatic
%>
<%inherit file="/card/base.html" />
<%namespace name="widgets" file="/card/widgets.html"/>
<%def name="title()">
404 Oops...
</%def>
```
Code in template's self-defined blocks is not correctly indented.
> add missing `web-mode-block-padding`

- editorconfig.el
This function will show editorconfig properties applied to current buffer, and just print message if editoconfig is not enabled yet for current buffer.
I think this function is useful for debugging: you can check
* If EditorConfig is properly enabled
* What properties have been applied to current buffer
> Add function editorconfig-display-current-properties

- editorconfig.el
> Add variable editorconfig-exclude-modes

- Makefile
This commit adds a new Make target `sandbox`.
Issue `make sandbox` to start new Emacs that loads *.el files in current
directory and does not load the user init file.
> Add make sandbox target

- README.md
Recently we do not update the package in Marmalade repository.
> Add link to MELPA Stable and deprecate Marmalade repository

- editorconfig-core-handle.el
#93 
Now error messages like the following will be shown.
Error (editorconfig): Error while reading config file: /home/a/editorconfig-emacs/.editorconfig:3:
[ab
.  Styles will not be applied.
> Print line number and its content on parse error

- editorconfig-conf-mode.el
- editorconfig.el
And moved some functions and definitions from editorconfig.el
editorconfig-mode and editorconfig-conf-mode are different features, so I think it is natural to separate those codes 🐵
> Add editorconfig-conf-mode.el

- editorconfig.el
Fix for the case where this plugin is installed with `git clone`.
Additionally, When the core library is not available, it will emit a
more friendly error message like:
Cannot open load file" "no such file or directory" "editorconfig-core"
#99
> Load editorconfig-core explicitly just becore use

- editorconfig.el
Why ?
--------
**In short**: Emacs always asks which charset to use when editorconfig-mode is enabled, .editorconfig does not exist and trying to save files with non-ascii characters (at least when the user init file is empty). This is an annoying behavior so stop it.
Calling `set-buffer-file-coding-system` sets the "explicit" flag, and it is used just before saving files.
When this flag is set but the charset is `undecided`, Emacs asks users what charset to use for saving files with non-ascii characters (when this flag is not set Emacs do not ask and decide
to use something automatically, `utf-8` for my environment).
This typically happens when editing files in repositories without .editorconfig, and it is a bit annoying behavior.
This change makes this plugin not call …
> Avoid askting coding system when neither charset nor end_of_line is specified

- .editorconfig
https://github.com/editorconfig/editorconfig-emacs/pull/108#issuecomment-258657021
Indentation of the code for this project is very different from the general Emacs Lisp indentation rules.  `indent_size` rule looks like bad affinity to Lisp.
```el
;; [*.el] indent_size = 2
(defun editorconfig-mode-apply ()
"Apply EditorConfig properties for current buffer.
This function do the job only when the major mode is not listed in
`editorconfig-exclude-modes'."
(when (and major-mode
(not (memq major-mode
editorconfig-exclude-modes))
buffer-file-name
(not (cl-loop for regexp in editorconfig-exclude-regexps
if (string-match regexp buffer-file-name) return t
finally return nil)))
(editorconfig-apply)))
;; General Emacs Lisp indentation
(defun editorconfig-mode-apply ()
"Apply EditorConfig properties …
```
> [proposal] Unset indent_size for editorconfig.el

- editorconfig.el
Warning occurred when you open a remote file.
```el
(find-file "http://httpbin.org/get")
```
The following error was encountered:
```
Error (editorconfig): .editorconfig/80 nodename nor servname provided, or not known.  Styles will not be applied.
```
`editorconfig-exclude-prefixes` behaves as a blacklist for `editorconfig-mode-apply`.
This is a simplistic solution.  Any ideas?
> Add editorconfig-exclude-prefixes

- editorconfig.el
F# is an open source, cross-platform, "functional-first" language, descendent
from the ML family.
The mode this commit adds support for is
https://github.com/fsharp/emacs-fsharp-mode (fsharp-mode on MELPA).
> Add support for fsharp-mode

- editorconfig.el
> By default always use Emacs Lisp Core when accessing remote files

- editorconfig.el
I'm not 100% sure about whether all these variables should be changed by editorconfig, but this should be every indentation setting in verilog. Let me know if I'm missing anything!
The variables I'm not sure about are `verilog-cexp-indent` and `verilog-case-indent`, which default to a different value from all the others, but I'm fairly sure that they control indentation (and therefore should be overriden by editorconfig indentation settings).
Thanks for looking at this! :smile:
> Add support for verilog-mode

- editorconfig.el
This PR adds support for [feature mode](https://github.com/michaelklishin/cucumber.el). 
It uses the variable `feature-indent-offset`, which is [defined here](https://github.com/michaelklishin/cucumber.el/blob/master/feature-mode.el#L330). Let me know if you spot any problems! :)
> Add support for feature mode.

- editorconfig.el
Set `fill-column` directly instead of using `set-fill-column`. That function is useful when used interactively, but when called from Lisp it’s almost equivalent to just setting `fill-column` directly, and it avoids showing the “Fill column set to…” message.
> Set `fill-column` directly

- editorconfig.el
that formats the buffer according to .editorconfig indent_style and indent_with
> add editorconfig-format-buffer function

- editorconfig.el
groovy-mode recently added its own indent variable:
https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/commit/1f3872e01f
> editorconfig-indentation-alist: fix groovy-mode

- .editorconfig
- README.md
- editorconfig-conf-mode.el
- editorconfig.el
https://github.com/editorconfig/editorconfig/issues/190
Fow now I just added support for `file_type_emacs` property (not a uniform name like `file_type`).
> Add experimental file_type_emacs support

- editorconfig.el
Change from `after-change-major-mode-hook' to
`change-major-mode-after-body-hook' to allow dir-local variables to
take precedence over editorconfig.
Please let me know if you see any issues, although I don't anticipate any change will occur for those not using dir-locals.
Closes #141
> Change hook editorconfig is applied on

- editorconfig.el
`buffer-file-name` can be programmatically set to anything, and if it points to something editorconfig(1) cannot deal with, the function gets the following error output.
```
Error (editorconfig): Input file must be a full path name.
.  Styles will not be applied.
```
I got the error when trying to use `helm-ag` with `helm-ag-use-temp-buffer` enabled.
> Avoid passing a non-absolute or non-existent file path to editorconfig(1)

- editorconfig-conf-mode.el
This adds additional syntax highlighting in `editorconfig-conf-mode` for the **unset**  property value.
Related to https://github.com/editorconfig/editorconfig-emacs/issues/156.
> Add syntax highlighting for unset property value.

- editorconfig.el
- ert-tests/editorconfig.el
- ert-tests/test_files_secondary/.editorconfig
- ert-tests/test_files_secondary/2_space.el
Sorry for the delay, I actually completely forgot about this...
I actually changed the spec of the variable from what I originally defined it as, the docstring is now:
```
Selectively ignore the value of indent_sizefor Lisp files.
Prevents `lisp-indent-offset' from being set selectively.
nil - `lisp-indent-offset' is always set normally.
t   - `lisp-indent-offset' is never set normally
(always use default indent for lisps).
number - `lisp-indent-offset' is not set only if indent_size is
equal to this number.  For example, if this is set to 2,
`lisp-indent-offset'will not be set only if indent_size is 2.
```
Let me know if anything seems wrong here, since this is a pretty large change.
Closes #137
> Add variable to disable lisp-indent-offset sometimes

- editorconfig-core-handle.el
- ert-tests/editorconfig-core-handle.el
- ert-tests/whitespaces/example-editorconfig.txt
Currently core-handle fails to parse files that contain whitespaces like line breaks, horizontal space, vertical space, etc.
Fixes #161
> Allow normal whitespace when reading EditorConfig settings file

- Makefile
During debian package build, the Makefile is called by debian/rules, which is also a Makefile. PWD is not propaged in recursive Makefile invocation, but CURDIR is:
https://www.gnu.org/software/make/manual/html_node/Recursion.html
found via: https://sourceforge.net/p/ipt-netflow/bugs-requests-patches/53/
> use CURDIR instead of PWD in Makefile

- editorconfig-fnmatch.el
Now editorconfig-fnmatch-translate will return only translated regexp string so that the return value can be used from external code much more easily.
> Refactor fnmatch-p 

- editorconfig-core-handle.el
- editorconfig-core.el
- ert-tests/editorconfig-core.el
With this the code will be much simpler:
https://github.com/editorconfig/editorconfig-core-test/pull/23
> Forget properties order

- Makefile
- README.md
- bin/editorconfig-el
- editorconfig-conf-mode.el
- editorconfig-core-handle.el
- editorconfig-core.el
- editorconfig-fnmatch.el
- editorconfig.el
- Follow MELPA guidelines
https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org
https://github.com/melpa/melpa/blob/master/.github/PULL_REQUEST_TEMPLATE.md
- Pass M-x checkdoc
- Pass package-lint
- Except for `1:1: warning: Including "Emacs" in the package description is usually redundant.`
- I want to keep this to say that editorconfig is an editor independent project and there are other packages/libraries/extensions for other editors
- Use lexical-binging: t
- Other document fixes
- 2019
> Update docs and metadata

- editorconfig.el
Adds indentation support for the following major modes:
- [enh-ruby-mode](https://github.com/zenspider/enhanced-ruby-mode)
- [haxor-mode](https://github.com/krzysztof-magosa/haxor-mode)
- [mips-mode](https://github.com/hlissner/emacs-mips-mode)
- [nasm-mode](https://github.com/skeeto/nasm-mode)
- [terra-mode](https://github.com/StanfordLegion/terra-mode)
- [kotlin-mode](https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode)
> Add more modes to editorconfig-indentation-alist

- editorconfig.el
I created a [new mode](https://gitlab.com/jgkamat/bpftrace-mode) for bpftrace, which is based on c-mode, and this patch adds support for indentation via `c-basic-offset`.
> Add support for bpftrace-mode

- CHANGELOG.md
- editorconfig-core-handle.el
- editorconfig-core.el
- editorconfig-fnmatch.el
- editorconfig.el
According to [the editorconfig specification][1],
> For any pair, a value of `unset` removes the effect of that pair, even if it has been set before. For example, add `indent_size = unset` to undefine the `indent_size` pair (and use editor defaults).
Yet, the test suite for editorconfig *cores* [indicates][2] that an editorconfig shouldn't ignore values of "unset", and should return them as-is.
Therefore it's up to editorconfig *plugins* to discard values of "unset" at the point of use.
Before this commit, the only place in the code where the value "unset" was checked for was in `editorconfig-set-major-mode-from-ext`, whereas in other places, such as `editorconfig-set-indentation`, it was not checked.
After this commit, values of "unset" are immediately removed from the properties …
> Always handle "unset" values as non-present

- editorconfig.el
TRAMP paths looks like `/method:user@host:/path/to/file`, per https://www.gnu.org/software/tramp/#Quick-Start-Guide .
> editorconfig-exclude-modes should start with "/"

- editorconfig.el
editorconfig via TRAMP over SSH causes find-file to lag, as it traverses up the remote file hierarchy, each step incurring a network roundtrip.
> Exclude files that are being edited via TRAMP over SSH

- editorconfig.el
Some buffers get confused if you keep setting their mode, one example
is git-rebase-mode. This is an example buffer of a class of
special-mode buffers which are usually (but not always) non-file
buffers. Either way these buffers are usually special purpose
interactive buffers that will only get confused if editorconfig tries
to mess around with them.
> editorconfig.el: skip special-mode buffers when applying (#246)

- Makefile
- README.md
- editorconfig.el
- ert-tests/editorconfig-2.el
- ert-tests/editorconfig.el
- Refactoring editorconfig-mode
- Temporarily drop file-type support
- Add editorconfig-2-mode to test a new mechanism of applying properties
> Refactoring & add editorconfig-2-mode for beta test

- editorconfig.el
rjsx-mode is a .jsx file mode. It uses js-indent-level to configure the depth of indentation.
> Add support for rjsx-mode

- editorconfig.el
Unfortunately, it seems like the fix in #241 wasn't quite enough - my .emacs.d is symlinked from another folder, and it seems like the recentf-save-file has all symlinks resolved - when quitting emacs I was asked about modifications in the true path, but the recentf-save-file was set to the non-symlink-resolved path.
Grabbing the truename of the file seems to fix this issue for me.
> Fix excluding the recentf-save-file when in a symlinked directory

- editorconfig.el
Hey there! This little PR addresses some documentation-related warnings revealed when loading this wonderful package. I hope this change is welcome despite not having filed an issue beforehand.
Suggestions are welcome!
> Constrain documentation strings to 80 chars

- editorconfig.el
Emacs 29 introduced tree-sitter and tree-sitter major modes for a number of languages (including typescript)
This PR fixes indentation settings for both .ts and .tsx files when using new major modes.
Probably it should fix https://github.com/editorconfig/editorconfig-emacs/issues/268, if Emacs 29 with tree-sitter is used there.
> Enable indentation for tree-sitter based typescript mode

- editorconfig.el
Similar to https://github.com/editorconfig/editorconfig-emacs/pull/282
This PR adds support for `json-ts-mode` introduced in emacs 29 for json + tree-sitter
> Add support for json-ts-mode

- editorconfig-conf-mode.el
- editorconfig-core-handle.el
- editorconfig-core.el
- editorconfig-fnmatch.el
- editorconfig.el
minor changes.
1. I prefer to place `emacs` dependency to the front. That's what most Elisp users would want to see first before using a package
2. Update copyright year
---
I saw this package supports very old versions of Emacs, is there any plan to upgrade the code base so it only supports more modern Emacs versions, maybe drop `24.x` and `25.x`? 😅 
cc @10sr @xuhdev
> chore: Place emacs dependency to the front

- .github/workflows/build.yaml
- .gitignore
- CHANGELOG.md
- Eask
- Makefile
- editorconfig-conf-mode.el
- editorconfig-core-handle.el
- editorconfig-core.el
- editorconfig-fnmatch.el
- editorconfig.el
- ert-tests/editorconfig-core-handle.el
- ert-tests/editorconfig-core.el
- ert-tests/editorconfig-fnmatch.el
- ert-tests/editorconfig.el
- ert-tests/metadata.el
As discussed in #285, this patch has no feature changes, only upgrading the codebase and style changes. I also added the CI for `macOS`  and `Windows`.
I've done the CI in my fork, see the result in https://github.com/jcs-PR/editorconfig-emacs/actions/runs/3794760896.
> Drop Emacs 24.x and 25.x

- editorconfig.el
I loaded all packages in my Emacs install that included the `-ts-` substring and then did a search for all variables containing `-ts-`, `indent` and `offset` to determine the collection of indent related variables for the new builtin Emacs tree-sitter modes. I've added them to the editorconfig mappings, keeping entries for the legacy mode indent variables when possible (in case anyone has user functions dependent on them).
So far I've confirmed these are correct for the following modes:
+ [X] c++-ts-mode
+ [X] c-ts-mode
+ [X] cmake-ts-mode
+ [X] csharp-ts-mode
+ [X] go-ts-mode
+ [X] html-ts-mode
+ [X] java-ts-mode
+ [X] rust-ts-mode
+ [X] toml-ts-mode
> Add indent variable associations for numerous tree-sitter modes

- editorconfig-core.el
- editorconfig.el
Fix a bunch of compilation warnings in Emacs 29 about wrong usage of unescaped single quotes in docstrings.
> Fix compilation warnings in Emacs 29

- editorconfig.el
Hi maintainer:
`editorconfig-emacs` missing the emacs-29's `js-ts-mode` indentation specification which I've made for this pull request.
Thanks.
> Add `js-ts-mode' spec to `editorconfig-indentation-alist'

- editorconfig.el
`delete` deletion is performed destructively here, use `remove` to avoid changing global `write-file-functions` value.
> fix write-file-functions default value

- editorconfig.el
Fix compile warning https://github.com/editorconfig/editorconfig-emacs/actions/runs/4655590115/jobs/8238372696#step:5:66
```
In editorconfig-set-indentation-python-mode:
editorconfig.el:414:36:Warning: assignment to free variable
‘python-indent-offset’
```
> fix: Fix compile warnings

- editorconfig.el
For https://github.com/godotengine/emacs-gdscript-mode/issues/48.
> Add support for gdscript-mode

- editorconfig.el
`when-let` depends on this.
Fixes #289
> Load subr-x when compiling

- editorconfig-core.el
- editorconfig.el
- Load subr-x in editorconfig-core, too
- It seems for some cases when-let will be expanded differently and when-let* can be used to avoid this
Fixes #289
> Fix when-let (again)

- editorconfig.el
https://launchpad.net/python-mode says:
> All development has been moved to GitLab:
> https://gitlab.com/python-mode-devs/python-mode
> Replace python-mode-devs URL

- editorconfig.el
Introduced in `emacs` in `b6659e98a4fcaa44477b64d7782243feca020418`.
> chore: add `lua-ts-mode`

- editorconfig.el
Add support for [php-ts-mode](https://github.com/emacs-php/php-ts-mode). This package is not yet available in any ELPA, but will be submitted to GNU ELPA in due course.
> Add php-ts-mode

- editorconfig.el
[`jsonian.el`](https://github.com/iwahbe/jsonian) is another  major mode for JSON that supports large file.
> Add jsonian-mode

- .github/workflows/build.yaml
nix-emacs-ci does not provide them any more.
> Exclude some versions from test target

- CHANGELOG.md
- editorconfig.el
There seems to be no bug caused by using the new version, so removing the switch to use the legacy implenentation 🙌
> Remove editorconfig-mode legacy version

- .github/workflows/build.yaml
Also change versions to unquoted, rename `emacs_version` to `emacs-version` and exclude windows-latest, snapshot in a nicer way
> feat: Include test on macos-11 below 28.x

- editorconfig-core-handle.el
- editorconfig-core.el
- editorconfig-fnmatch.el
This tries to improve a bit the code of `editorconfig-fnmatch` and `editorconfig-core-handle--parse-file`.
> Eliminate some o n2

- README.md
- editorconfig.el
As noted in the documentation, `insert_final_newline = false` is expected to remove final newlines, but `editorconfig-mode` does not do that.
Use a similar pattern to `editorconfig-set-trailing-ws` by setting a buffer-local before-save hook to remove any final newline.
---
Fix #360.
> Finish support for insert_final_newline

- editorconfig.el
- ert-tests/editorconfig-tests.el
Until now, the file's coding system was set via an advice on `insert-file-contents`, which depends on being called from within the `find-file-noselect` advice.
While it mostly works, it doesn't account for all the cases (e.g. it fails to be used when doing `write-region`), is a bit cumbersome, and does not interact well with Emacs's other ways to specify a coding-system, such as `auto-coding-alist`.
This patch replaces it with an advice on `find-auto-coding`, so as to integrate better with the rest of Emacs's handling of files' coding systems.  An immediate benefit is that we don't need to special case jar and zip files any more because `auto-coding-alist` does it for us already (and for many more file types like tar, exe, ...).
* editorconfig.el (editorconfig-merge-coding-systems): Use …
> editorconfig.el: Hook elsewhere for the coding-system

- CONTRIBUTORS
- editorconfig-core-handle.el
- ert-tests/editorconfig-core-handle-tests.el
- ert-tests/fixtures/handle2.ini
While working on [zsa/qmk_firmware](https://github.com/zsa/qmk_firmware), I ran into the following error related to parsing the listed section header line:
```
editorconfig-error: Error thrown from editorconfig lib: "Error from editorconfig-get-properties-function: (editorconfig-error \"Error from editorconfig-get-properties-function: (error \\\"Error while reading config file: /home/.../qmk_firmware/.editorconfig:14:
[{*.yaml,*.yml}] # To match GitHub Actions formatting
\\\")\")"
```
While having a trailing comment on a section header line is unusual, to my knowledge, it is not forbidden. This change patches the relevant regexp using the optional comment pattern from the `cond` clause immediately above it.
> Fix parsing section lines with trailing comments

- editorconfig.el
Emacs 30 uses `js-json-mode` for JSON files which [no longer derives from][1] `js-mode`.
[1]: https://cgit.git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS?h=emacs-30#n1521
> Indent for js-json-mode

- editorconfig-fnmatch.el
This should make the generated regexes a little bit neater.
> editorconfig-fnmatch: improve ** globs
